plugins {
    id 'java'
    id 'org.openjfx.javafxplugin' version '0.1.0'
    id 'org.jetbrains.kotlin.jvm'
}

group = 'minecraft.morningmc'
version = '0.5.3.1'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.apache.logging.log4j:log4j-core:2.19.0'
    implementation 'dev.dewy:nbt:1.5.1'
    implementation 'com.google.code.gson:gson:2.11.0'
    implementation 'com.moandjiezana.toml:toml4j:0.7.2'
    implementation 'org.openjfx:javafx-web:21'
    implementation 'net.sf.jopt-simple:jopt-simple:6.0-alpha-3'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    compileOnly 'org.jetbrains:annotations:24.1.0'
}

jar {
    destinationDirectory.set(file("$rootDir/run/cores"))
}

kotlin {
    jvmToolchain(21)
}

configurations
        .matching(it -> it.name.contains("downloadSources"))
        .configureEach {
            attributes {
                attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage, Usage.JAVA_RUNTIME))
                attribute(OperatingSystemFamily.OPERATING_SYSTEM_ATTRIBUTE, objects.named(OperatingSystemFamily, "runtime"))
                attribute(MachineArchitecture.ARCHITECTURE_ATTRIBUTE, objects.named(MachineArchitecture, MachineArchitecture.X86_64))
            }
        }

tasks.register("compileWrapper") {
    group = "mcli"
    doLast {
        final executable = "mcli.exe"

        Process installer = new ProcessBuilder(
                "pyinstaller",
                "--distpath",
                "$rootDir/build/tmp/pyinstaller/dist",
                "--specpath",
                "$rootDir/build/tmp/pyinstaller",
                "--workpath",
                "$rootDir/build/tmp/pyinstaller",
                "--clean",
                '-y',
                "-n",
                executable,
                "-w",
                "-i",
                "$rootDir/src/main/resources/assets/textures/icon.png",
                "$rootDir/src/wrapper/main.py"
        ).start()
        installer.getInputStream().transferTo(System.out)
        installer.getErrorStream().transferTo(System.err)
        println "Pyinstaller exited with code ${installer.waitFor()}."

        mergeDirectories(new File("$rootDir/build/tmp/pyinstaller/dist/$executable"), new File("$rootDir/run"))
    }
}

static void mergeDirectories(File source, File target) {
    File[] files = source.listFiles()
    if (files != null) {
        for (File file : files) {
            File targetFile = new File(target, file.getName())

            if (file.isDirectory()) {
                targetFile.mkdir()
                mergeDirectories(file, targetFile)
            } else {
                file.renameTo(targetFile)
            }
        }
    }
}